import os
from dotenv import load_dotenv
from pinecone import Pinecone, ServerlessSpec
from openai import OpenAI

load_dotenv()

pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))
openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def get_embedding(text):
    response = openai_client.embeddings.create(
        input=text,
        model="text-embedding-3-small"
    )
    return response.data[0].embedding

def setup_index():
    index_name = os.getenv("PINECONE_INDEX_NAME")
    existing = [i.name for i in pc.list_indexes()]
    if index_name not in existing:
        print(f"Creating index '{index_name}'...")
        pc.create_index(
            name=index_name,
            dimension=1536,
            metric="cosine",
            spec=ServerlessSpec(cloud="aws", region="us-east-1")
        )
        print("Index created.")
    else:
        print(f"Index '{index_name}' already exists.")
    return pc.Index(index_name)

def index_chunks(index, chunks):
    print(f"Embedding and indexing {len(chunks)} chunks...")
    vectors = []
    for i, chunk in enumerate(chunks):
        print(f"  Chunk {i+1}/{len(chunks)}: {chunk['id']}")
        embedding = get_embedding(chunk["text"])
        vectors.append({
            "id": chunk["id"],
            "values": embedding,
            "metadata": {
                "text": chunk["text"],
                "category": chunk["category"]
            }
        })
    index.upsert(vectors=vectors)
    print(f"Done! {len(vectors)} chunks indexed.")

CHUNKS = [
    {"id": "brand-1", "category": "brand", "text": "Studio Lou is an interior design and growth marketing consultancy founded and run solely by Lauren. Phoenix-based, fully virtual practice. Lauren has 10 plus years of experience including stints at West Elm, Visual Comfort, Havenly, and boutique design firms. She holds degrees in both marketing and interior design. Studio Lou serves two primary audiences: homeowners seeking e-design services, and interior design firms seeking marketing strategy. The business also functions as a hidden portfolio for hiring managers at home and lifestyle DTC brands but this audience is never addressed directly in content."},
    {"id": "brand-2", "category": "brand", "text": "The Studio Lou voice brief: biased, opinionated, professional advice to a friend. Not generic. Not listicle. Warmer than the Wall Street Journal, sharper than a Pinterest caption. The wedge over competing content is that Lauren has actually done the thing she is writing about. Take positions."},
    {"id": "brand-3", "category": "brand", "text": "Studio Lou hard voice rules: No em dashes ever anywhere. No short staccato sentence strings. Do not default to the word curious in CTAs or closing lines. No performative humility. Do not describe the primary audience in third person in content directed at them. Never fabricate specific personal details. Do not repeat the same verb across nearby paragraphs. Never state a statistic without verifying it."},
    {"id": "brand-4", "category": "brand", "text": "Studio Lou voice person rules: Use we for general strategic claims and designer judgments. Use I for genuine personal disclosure such as Gavin, lived workspace experience, specific client observations. Use my clients not our clients when referring to Lauren's client relationships."},
    {"id": "brand-5", "category": "brand", "text": "Studio Lou visual brand system: papercraft and collage aesthetic. Primary palette: burgundy #582b36, linen warm off-white #e7dbbf, sage green, slate. Typography: DM Sans Bold for headlines, Crimson Pro for editorial body, BiroScript Plus for handwritten accent. Carousel templates: Editorial Week 1, Data Insight Week 2, Comparison Week 3, List Week 4. Export dimensions: LinkedIn and Instagram feed 1080x1350 (4:5 portrait). Instagram square is retired. Reels and TikTok video 1080x1920 (9:16). Carousel slides must all match the aspect ratio set by the first slide."},
    {"id": "brand-6", "category": "brand", "text": "Studio Lou tone by platform: Blog is professional advice to a friend, take positions, earned authority. LinkedIn is opinionated professional thought leadership, first-person credibility moments land well. Instagram is warmer and slightly more aspirational than LinkedIn, still opinionated not generic lifestyle. Pinterest is keyword-forward with credibility signal plus click hook. TikTok is most direct and personal, conversational, honest about what does and does not work."},
    {"id": "brand-7", "category": "brand", "text": "The Adapt-First Principle: before building anything from scratch, ask whether something already exists that can be adapted. Hierarchy: adapt existing content for a new platform first, extend or remix with a new angle second, build new from scratch only when neither serves the goal."},
    {"id": "ops-1", "category": "ops", "text": "Studio Lou four-month thematic arc: Month 1 AI x Interior Design, differentiator and highest-volume search topic. Month 2 Home Office Design, strongest performer, runs during heavy job-hunt period. Month 3 Marketing for Designers, hiring-manager bait, deployed when applications hit interview stage. Month 4 Startup and Modern Office Design, rounds out the year, bridges back to AI for SF startup audience."},
    {"id": "ops-2", "category": "ops", "text": "Studio Lou sprint week model: each month's full content output is produced in a single sprint week producing 3 to 4 full blog drafts, 4 hero carousels, 20 to 28 Pinterest pins, 4 TikTok slideshows, all captions for all platforms, and 1 to 2 TikTok reaction videos. Posting weeks that follow are kept light."},
    {"id": "ops-3", "category": "ops", "text": "Studio Lou posting cadence: LinkedIn 3 posts per week, Tuesday hero carousel, midweek text post, Friday single image or recap. Instagram 3 posts per week, Tuesday hero carousel, Thursday Reel or single image, Saturday lifestyle softener Week 1 or quick design tip Weeks 2 to 4. Pinterest 5 to 7 pins per week Monday through Saturday, no hashtags. TikTok 2 videos per week. Blog 1 hero post per week live Monday."},
    {"id": "ops-4", "category": "ops", "text": "Studio Lou scheduling tools: Buffer handles LinkedIn and TikTok, free tier 3 channels 10 posts per channel in queue. Meta Business Suite handles Instagram, free unlimited. Pinterest native scheduler used for Pinterest, free unlimited, native scheduling gets slightly better algorithmic reach."},
    {"id": "ops-5", "category": "ops", "text": "Studio Lou hashtag rules: Instagram has a hard five-hashtag cap enforced December 2025. Pinterest uses no hashtags, Pinterest stopped indexing them in 2022. LinkedIn performs best with three to five hashtags. Never use save this on LinkedIn."},
    {"id": "ops-6", "category": "ops", "text": "Studio Lou growth strategy: Pinterest is the strongest traffic driver. Reels are the only Instagram format reaching new audiences at current follower scale. Contrarian LinkedIn posts show the clearest engagement signal. TikTok reaction videos have higher organic reach potential than slideshows at small follower counts. The Zoom Backgrounds post is the strongest full-funnel asset."},
    {"id": "blog-1", "category": "blog", "text": "Every Studio Lou hero blog follows this skeleton in order: thumbnail summary, category label, H1 SEO-optimized, At a Glance table placed immediately after H1 before any prose, opening hook H2 250 to 300 words, H2 body sections in prose, conclusion H2 SEO-optimized not generic Final Thoughts, CTA either its own H3 formatted as Want Help Doing the Thing or folded into conclusion 120 to 150 words."},
    {"id": "blog-2", "category": "blog", "text": "The At a Glance table is a structural signature of every Studio Lou hero blog, NOT optional. Format: two-column table placed immediately after the H1, before any prose. Top row is a single At a Glance label spanning both columns, no other header row. Body cells contain ALL post H2 section titles flowing left-to-right then top-to-bottom in post order. This is NOT a Section Description table, NOT a comparison table, NOT a single-column list. Section titles only, two-column flow."},
    {"id": "blog-3", "category": "blog", "text": "Studio Lou blog word count targets: Opening hook approximately 250 to 300 words. Major body sections approximately 400 to 700 words each. Bridge sections approximately 300 to 400 words. Conclusion approximately 150 to 200 words. CTA approximately 120 to 150 words. Total hero post target 2400 to 2800 words. Blog drafting is always section by section, wait for sign-off before moving to the next section. Include word count at the end of each section."},
    {"id": "blog-4", "category": "blog", "text": "Studio Lou CTA standards: approximately 120 to 150 words. Conversational, slightly self-aware about what the reader is feeling. Single bold link: Get in touch with Studio Lou here linking to https://www.studiolouinteriors.com/contact. Do not default to curious. Pattern: acknowledge what reader is feeling, explain how Studio Lou is built for that gap, name one specific thing Studio Lou does, close with link."},
    {"id": "blog-5", "category": "blog", "text": "Studio Lou linking rules: Internal links maximum 3 per post, deploy near end of body or in conclusion not intro. Outbound citations minimum 2 to 3 per post, no ceiling, more citations are always welcome when sources are verified. Preferred sources: institutional such as Steelcase, BLS, Stanford, Harvard Business Review; trade press such as Apartment Therapy, Dwell, Livingetc, Domino, Business of Home. Never placeholder a stat, verify before including."},
    {"id": "blog-6", "category": "blog", "text": "Studio Lou blog formatting: Default format is prose paragraphs, no bullets unless structure is genuinely list-shaped. Bold lead-ins for parallel entities within a prose section. No H3 subheadings inside major sections unless they need their own keyword targeting. No em dashes anywhere. Smart quotes throughout. Concrete details over abstractions."},
    {"id": "blog-7", "category": "blog", "text": "Pinterest pin description three-part formula: 1. Keyword phrase up front targeting Pinterest search algorithm. 2. Credibility marker positioning Studio Lou as authority. 3. Click hook giving reader a reason to tap through. Example: Home office lighting ideas for productivity, most remote workers get this wrong. Studio Lou breaks down the lighting setup that actually improves focus. Full guide on the blog."},
    {"id": "persona-1", "category": "persona", "text": "Studio Lou primary audience: design-curious homeowners who want a designed space without hiring a traditional full-service firm. DIY-adjacent, budget-conscious to mid-range. Find Studio Lou primarily through Pinterest and Instagram. Respond to content that gives genuine insight from a real designer who lives in a real space. Primary audience for home office content, e-design services, and lifestyle-adjacent posts."},
    {"id": "persona-2", "category": "persona", "text": "Studio Lou secondary audience: solo or small interior design firms who are strong on design execution but under-resourced on marketing. Looking for strategy, systems, and specific tactics, not generic business advice. Most active during Month 3 Marketing for Designers content. Find Studio Lou through LinkedIn, blog search, and design industry channels."},
    {"id": "persona-3", "category": "persona", "text": "Studio Lou hidden tertiary audience: hiring managers at home and lifestyle DTC brands including Lulu and Georgia, Minted, Thrive Market. This audience is NEVER addressed directly in content and never named in posts. It is a structural layer only. The Studio Lou blog reads as a marketing case study in aggregate."},
    {"id": "persona-4", "category": "persona", "text": "Studio Lou fourth audience: business owners and startup founders who care about how design decisions affect work performance, client perception, and productivity. Primary audience for Month 4 Startup and Modern Office Design. Respond to ROI framing and content that bridges aesthetic decisions with business outcomes."},
    {"id": "archive-1", "category": "archive", "text": "Lauren and Gavin share a home office, both desks on the same wall. Lauren setup: Uplift standing desk, monitor and laptop on dual-monitor stand, lighter residential chair not an Aeron, Article console, filing cabinet, wall shelving, linen pinboard. Gavin setup: wider Uplift standing desk, Herman Miller chair, single BenQ monitor with built-in KVM switch, Mac mini, custom PC to the left, laptop and iPad tucked away, dry-erase board, steel pegboard. Always refer to Gavin as Lauren's boyfriend in blog body copy, never partner."},
    {"id": "archive-2", "category": "archive", "text": "Gavin works remotely in growth marketing at HelloData, a B2B multifamily SaaS company, approximately two years at current company. Day includes 7am all-hands, internal training calls, monitoring and optimizing HubSpot campaigns and ad campaigns. Does NOT do extensive async Slack or docs writing. Always refer to him as Lauren's boyfriend, never partner."},
    {"id": "archive-3", "category": "archive", "text": "Month 1 AI x Interior Design: four blogs covering AI tools for interior design tested comparison of 8 tools, real design workflows using AI, AI marketing stack for design firms, AI limits in design. Month 1 established sprint week system, carousel template library, visual brand system, all platform posting conventions."},
    {"id": "archive-4", "category": "archive", "text": "Month 2 Home Office Design: four blogs covering shared home office layouts for two-worker households written from Lauren and Gavin real setup, the startup remote worker setup, creative work home offices, home office mistakes. Strongest-performing content month. Content operations reference document built during Month 2."},
    {"id": "archive-5", "category": "archive", "text": "Month 3 Marketing for Designers: four blogs covering positioning strategy for design firms, content systems for design practices, visibility channels for interior designers, discovery and intake. Deployed during active job application and interview phase. Website copy audit completed. Social bios rewritten across all four platforms."},
    {"id": "archive-6", "category": "archive", "text": "Month 4 Startup and Modern Office Design complete. Blog 1: Why Your Team Isn't Using the Office, return-to-office design failures, startup identity thread woven throughout. Blog 2: The Startup Office Acoustics Guide, anchor stat is Cornell research on subconscious stress responses to noise. Blog 3: What a Startup Office Actually Costs, budget breakdown by stage, pivoted from tiered spend tiers to advice-forward framework mid-production. Blog 4: AI in Commercial Interior Design What's Working What's Risky and Why 2026 Is a Turning Point, reframed mid-draft from startup founder audience to commercial designers and architects, moved to AI x Interior Design category, journalist editorial register, technical language RAG multimodal agentic MCP woven in after plain-language setup. All four weeks of social content produced."},
    {"id": "archive-7", "category": "archive", "text": "Studio Lou technical infrastructure: website built on Framer. TikTok production uses CapCut, desktop upload workaround for Reels compatibility. Blog headers built in Canva papercraft collage aesthetic. Carousel templates built in Canva. Buffer for LinkedIn and TikTok scheduling free tier. Meta Business Suite for Instagram. Pinterest native scheduler. Lauren also sells papercraft-style vector graphics on Gumroad and Etsy."},
    {"id": "carousel-editorial", "category": "ops", "text": "Studio Lou Editorial carousel template: used for contrarian take or reframe weeks. Slide 1 Cover: bold claim in a this-not-that or we-tested-we-found format, one sentence, folder backdrop tilted. Slide 2 Thesis: one short paragraph restating the problem in the reader's terms, we voice, no lists. Slides 3-5 Points: one insight per slide, bold sage green lead-in, 2-4 lines of copy, photo optional. Slide 6 Counterpoint: optional qualifier when thesis needs nuance. Slide 7 CTA: Studio Lou verdict 1-2 sentences, full breakdown on the blog link in bio, clipboard element straightened not tilted, logo prominent."},
    {"id": "carousel-datainsight", "category": "ops", "text": "Studio Lou Data Insight carousel template: used for weeks with a strong stat or research finding. Slide 1 Cover: reframe headline challenging a common assumption, burgundy background, clipboard tilted, annotation green handwriting. Slide 2 Stat: single research finding large, source in annotation green handwriting, brief explanatory sentence. Slides 3-4 Toolkit: 2-3 solutions per slide, sage green bold lead-in, clipboard backdrop straightened on screenshot-heavy slides. Slide 5 Framework: prioritization logic, numbered sequence or cost-impact in plain text. Slide 6 What It Won't Fix: honest scope-setting, brief, reinforces authority. Slide 7 CTA: verdict line, blog CTA, real office photo. Two-green system: sage green for brand elements, brighter annotation green for handwritten callouts."},
    {"id": "carousel-comparison", "category": "ops", "text": "Studio Lou Comparison carousel template: used for two-option, before-after, spend-vs-save, or stage-by-stage weeks. Slide 1 Cover: stakes-first headline, specific and numbers-adjacent. Slide 2 Frame: establishes the comparison axis. Slides 3-5 Comparison units: one comparison per slide, adapt layout to blog structure rather than forcing a strict two-column split. Slide 6 Rule of thumb: one heuristic the reader walks away with, bold lead-in. Slide 7 CTA: verdict, blog CTA, clipboard element. Template flexibility is a feature, structure always serves content not the other way around."},
    {"id": "carousel-list", "category": "ops", "text": "Studio Lou List carousel template: used for ranked or enumerated tools, fixes, or recommendations. Slide 1 Cover: number plus bold claim, teases the list. Slide 2 Bridge: why this list matters, 2-3 sentences, sets stakes. Slides 3-6 List items: one item per slide, oversized number top-left (01 02 03), bold item name, 2-4 lines of copy, sage green lead-in word, no photography required. Slide 7 Verdict: earned takeaway not just a recap, blog CTA, clipboard element. Typography carries this template."},
    {"id": "carousel-shared-rules", "category": "ops", "text": "Studio Lou carousel shared rules: dimensions 1080x1350 for LinkedIn and Instagram feed. All slides must match the first slide aspect ratio. Fonts: DM Sans Bold headlines, Crimson Pro subheads, BiroScript Plus handwritten annotations. Colors: burgundy, linen or cream background, sage green for brand elements, brighter annotation green for handwriting. Logo bottom-right or bottom-center on every non-cover slide. Slide 7 CTA: clipboard element always straightened not tilted. No em dashes in any slide copy. No week numbers or series labels on client-facing slides. TikTok variant uses a tighter punchier hook on the cover slide."},
    {"id": "header-marketing", "category": "ops", "text": "Studio Lou blog header template for Marketing for Designers category: linen background, clipboard as title surface, burgundy accents, binder clips, index cards, pen. Stock photo direction: meeting or consultation, desk setup, someone reviewing documents. Feel: strategic, slightly editorial, professional but warm. Variable text slots per post: subtitle line, polaroid caption, sticky note text, index card text."},
    {"id": "header-ai", "category": "ops", "text": "Studio Lou blog header template for AI x Interior Design category: charcoal #433E3C background, spiral notebook on green cutting mat, calculator, triangle ruler, small robot doodle on index card. Stock photo direction: AI interface screengrab, design software, tech-meets-design visual. Feel: analytical, slightly editorial, signals technical rigor not surface-level trend content. Variable text slots per post: subtitle line, polaroid caption, sticky note text, index card text."},
    {"id": "header-homeoffice", "category": "ops", "text": "Studio Lou blog header template for Home Office category: linen background with warm wood desk surface bleeding in from bottom, open spiral notebook as title surface, coffee mug, keyboard, plant, sage green sticky note. Stock photo direction: real home office setup, ideally Lauren and Gavin's shared office. Feel: functional, calm, warm productivity, residential but serious. Variable text slots: subtitle line, polaroid caption, sticky note text, index card text."},
    {"id": "header-startup", "category": "ops", "text": "Studio Lou blog header template for Startup and Modern Office category: grid paper background, manila folder as title surface, dry erase board with org chart or floor plan doodle, paper airplane, stapler. Stock photo direction: real commercial office interiors, reference offices include Mortenson Tempe, New Lab Brooklyn, Nvidia Voyager and Endeavor Santa Clara, Wise London, Dice London. Feel: systematic, commercial, slightly strategic."},
    {"id": "header-budget", "category": "ops", "text": "Studio Lou blog header template for Design on a Budget category: beige #E7DBBF background with corkboard behind main element, grid notebook pinned to corkboard, paint palette swatches, fabric swatch, flowers or tulips, candle, DIY washi tape lettering. Stock photo direction: accessible beautiful interiors, rental-friendly spaces, before and after transformations. Feel: warm, tactile, crafty, washi tape lettering is the key visual differentiator. Variable text slots: subtitle line, polaroid caption, sticky note text, washi tape label."},
    {"id": "caption-linkedin", "category": "ops", "text": "Studio Lou LinkedIn caption formula: Line 1 hook is emoji plus one bold claim or counterintuitive statement, must work before the more cutoff, no em dashes, no hedging. Lines 2-3 context and stakes, 1-2 sentences. Lines 4-8 substance in listicle format using arrows or numbers. Second to last line blog CTA, currently omitting URLs during link suppression test, using full breakdown on the blog link in bio. Last line comment-driving question specific to the post topic. Hashtags 3-5 at end. One emoji per post at hook opening, non-repeating across the week. Never use save this on LinkedIn. Voice is always we for Studio Lou."},
    {"id": "caption-instagram", "category": "ops", "text": "Studio Lou Instagram caption formula: Hook mirrors the carousel cover line or a warmer version of the LinkedIn hook, more conversational. Lines 2-5 story or argument in short flowing paragraphs, Instagram audiences expect longer warmer captions than LinkedIn. Middle block actionable insight or key takeaway. Second to last block save this for specific use case prompt or swipe CTA, low-friction and playful. Last line hashtags, hard cap 5 maximum enforced December 2025. No em dashes. No time-bound language. Voice is we for studio content, I or my only for Lauren's specific personal moments."},
    {"id": "caption-tiktok", "category": "ops", "text": "Studio Lou TikTok caption formula: on-screen hook on slide 1 or first 2 seconds is the primary strategy, must work as scroll-stopper before anyone reads the caption. Caption line 1 is one-sentence complement to the hook. Caption line 2 is full guide on the blog link in bio always. Hashtags 3-5, mix one broad tag with one niche tag and one platform tag such as designtok or fyp. Total caption 2 lines max before hashtags. Caption sweet spot 50-150 characters for engagement, longer captions help TikTok SEO. Slideshows adapt from Instagram carousel using the punchier TikTok hook angle."},
    {"id": "caption-pinterest", "category": "ops", "text": "Studio Lou Pinterest description formula: Part 1 keyword phrase up front targeting Pinterest search. Part 2 credibility marker one sentence separating this pin from generic content in the same search. Part 3 click hook a specific promise implying more without giving the answer away. No hashtags. Pin titles short keyword-rich sentence-case max 60 characters. Alt text required, describe image content specifically. Descriptions must sound human-written, keywords woven in naturally not front-loaded as a tag dump. Pinterest is a search engine not a social platform. Pins scheduled natively one per day, never through Buffer."},
    {"id": "ops-crosspost", "category": "ops", "text": "Reels and TikTok crossposting strategy: when a video concept works for both Instagram Reels and TikTok, produce it once and post to both. Fit determines it not a schedule, does not need to happen every week. Format 1080x1920 9:16 same file works on both platforms. Always write separate captions per platform even when the video is the same. Hashtag sets differ slightly between platforms. Do not crosspost when the hook or format is highly platform-specific. Applies in both directions, TikTok-first content that works on Instagram should be repurposed as a Reel."},
    {"id": "ops-platform-specs", "category": "ops", "text": "Studio Lou platform specs confirmed June 2026: Instagram feed and carousel 1080x1350 4:5 portrait, square 1:1 retired. Reels and TikTok 1080x1920 9:16, keep key content inside central 1080x1350 safe zone. LinkedIn carousel 1080x1350. Instagram caption limit 2200 characters, first 125 visible before more cutoff. TikTok caption sweet spot 50-150 characters. Platform rules shift regularly, verify current standards at the start of any new production session rather than relying on prior-month rules."},
    {"id": "ops-citations", "category": "ops", "text": "Studio Lou external citation rule: minimum 2 to 3 strong outbound citations per blog post, no ceiling. More citations are always welcome when they add authority and sources are verified. Never placeholder a statistic. Verify the source and exact claim before including it in any draft. If a source cannot be verified, the stat does not go in. Citations formatted as inline hyperlinks, never footnotes."},
    {"id": "ops-standing-corrections", "category": "ops", "text": "Studio Lou standing corrections: em dashes banned in all content, check every section before returning it. Save this belongs on Instagram only never LinkedIn. Instagram hashtag cap is 5 maximum enforced December 2025. LinkedIn hashtags 3-5 max. No series or week labels in public content, every post stands alone. No time-bound language in blog copy. At a Glance table is two-column with At a Glance spanning the top row, H2 titles flowing left-to-right top-to-bottom in post order, shortened to fit one line, conclusion H2 not included. Internal links flagged proactively during drafting not retrofitted at end. Instagram images are 4:5 not square. External citations have no upper limit, more is better when verified."},
]

if __name__ == "__main__":
    print("Setting up Studio Lou RAG...")
    index = setup_index()
    index_chunks(index, CHUNKS)
    print("\nStudio Lou knowledge base is live in Pinecone!")